public class OOPConcepts 
{
 //---------------------------------------------------demo of constructor----------------------------------------------------
    public OOPConcepts(Integer takeInput)
    {/*
        Integer takeInput= takeInput;
        system.debug('Constructor executed :value of input = '+this.takeInput);*/
        
        Integer input= takeInput;
        system.debug('Constructor executed :value of input = '+input);
    }
}